### ISSUE TITLE
building local website

### ISSUE THREAD

**Issue by piks3l** [Netzfreiheit/STI-UI#107]
I'm on debian jessie and I have wierd issue in launching the website local. I have installed hugo and go, I launched the configuration as it was said on the readme but

:~/Documents/STI/STI-UI$ hugo server --config config_fr.yaml --verbose
Error: flag needs an argument: --config
Run 'hugo help' for usage.
CRITICAL: 2016/04/04 flag needs an argument: --config

~/Documents/STI/STI-UI$ cat config_fr.yaml 
baseurl:    "https://savetheinternet.eu"
title:      "SAVE THE INTERNET"
contentdir: "content/fr"
publishdir: "public/fr"
theme:      "sti"

params:
  language: "fr"

I never worked with hugo, so sorry if my question could seem silly. 

Cheers !

**Comment by musha68k** [comment]
🇫🇷 Salut @piks3l ! 

I started from scratch today to reproduce this issue but didn't run into it, could you do me a favour and fetch and diff your translation efforts with the German translation branch?

https://github.com/Netzfreiheit/STI-UI/tree/translation-de

Merci beaucoup!
