### ISSUE TITLE
Images transaltion

### ISSUE THREAD

**Issue by AlfaSchz** [Netzfreiheit/STI-UI#110]
at least net_neutrality_roadmap.svg and save_the_internet_logo_headline.svg should be translatable. 
translations could follow the aproach:
net_neutrality_roadmap_[TWO_LETTER_CODE].svg
save_the_internet_logo_headline_[TWO_LETTER_CODE].svg

Road map's text areas are editables but not so headline logo, even thoug it is an svg
Also a .txt file with font names & sources could help.

**Comment by musha68k** [comment]
Hi @AlfaSchz short update - we will be discussing some topics which will touch upon this. I'll ping you when we are ready for the translation of the image assets (probably will change to even more plain old HTML/CSS instead)..

**Comment by socialhack** [comment]
We should keep this in mind with any image changes.

**Comment by PublicScam** [comment]
Fixed in commit 92c1f18a373d5a3162301e293af7bf6d3ecf5d41.
