### ISSUE TITLE
Process for translating iframe tool?

### ISSUE THREAD

**Issue by AlfaSchz** [Netzfreiheit/STI-UI#111]
I know this is the front end of the site but any tips on what should be the process for translating the questionare?

**Comment by maltefiala** [comment]
A question for @filipesousa20 and @ondrejpialek , see https://github.com/EndzoneSoftware/STI/issues/16

**Comment by socialhack** [comment]
@AlfaSchz I would be careful with translating the questionnaire. AFAIK BEREC has no additional translation staff, sending them comments in multiple languages could overload them completely. I'd suggest only offering the questionnaire in English and French.

**Comment by musha68k** [comment]
This is somewhat backend related, I'm closing this for now (pls re-open if you feel this is more of an STI-UI issue after all).
