### ISSUE TITLE
Request for review of German translation (German speakers)

### ISSUE THREAD

**Issue by musha68k** [Netzfreiheit/STI-UI#113]
See [staging site](https://beta.savetheinternet.eu/de/) and branch "translation-de":

https://github.com/Netzfreiheit/STI-UI/tree/translation-de

Dankeschön!

**Comment by socialhack** [comment]
There are many formulations which require more work to be good campaign language in german. 

How can people change the german translation of this site? Please provide a short explanation how people can help.

**Comment by sebalis** [comment]
I’m willing to work on it, have forked the repository and cloned it to my local disk. How do I run the website locally so I can see the translation and my changes in a “live” view?

**Comment by sebalis** [comment]
Sorry to bother you, I got the server to run using the instructions in the readme.

**Comment by sebalis** [comment]
How do we internationalise the "ACT NOW" button? It is currently hard-coded into themes/sti/static/images/act_now*.* (three files).

**Comment by sebalis** [comment]
Pull request #114 submitted with a first set of changes. Some open questions remain, one is the one about assets and the other is how to deal with the questionnaire. I notice that a translated file “questions-form-header.html” exists in the “partials” folder but I could not see on my local version of the site as I was running hugo. (I have to praise the developers for the simplicity of the setup by the way :-) at least for this Linux user with some technology experience)

**Comment by sebalis** [comment]
I had somehow overlooked the file home-info.html, which contains a major part of the text of course. Now added to the pull request. I’m still not touching anything regarding the questionnaire as I don’t know how to see the changes locally. This applies to the country/language switcher above the IFrame as well – it seems to get loaded from the online site and I don’t yet see how to change that as well as the IFrame URL. Help would be appreciated.

**Comment by sebalis** [comment]
Thanks to @zomtec for reviewing and commenting my changes. As a result I added three further commits to the pull request. Still waiting for guidance on how we should communicate the language restrictions for submissions to BEREC and, if desired, how to internationalise the country and language switcher (i.e. how can I see local changes on my local server in for double-checking). Also, I see that the FAQ hasn’t yet been translated into German by any of the three German translators. Again, before I start on that I’d like to be able to see the changes on my local server that’s running on the translation-de branch, but clicking the FAQ link only produces a 404 message. Please help :-)

**Comment by sebalis** [comment]
I discovered how to view the FAQ locally by reading pull request #108: just delete the language component from the path, http://localhost:1313/faq/ works. I will start working on the FAQ later (probably not before tomorrow German time) and announce it by adding another comment. If someone else would like to start before me, please follow the same protocol (add a comment here) in order to avoid duplicate work as in pull request #116.

**Comment by musha68k** [comment]
FYI latest changes viewable on [staging](https://beta.savetheinternet.eu/de/)

Dankeschön!

**Comment by digitalegesellschaft** [comment]
Hi, we at Digitale Gesellschaft were asked to check the German translation's wording. I have some suggestions now but am a Github-newbie, so I'd like to ask if someone could give me a brief introduction on how to edit without messing up everything. Thanks!

**Comment by sebalis** [comment]
I’m on the phone to digitalegesellschaft now, will probably commit changes for them soon.

**Comment by sebalis** [comment]
Changes committed as pull request #124.

**Comment by musha68k** [comment]
Awesome @sebalis your latest changes have been deployed to [staging](https://beta.savetheinternet.eu/de/)

**Comment by socialhack** [comment]
I would recommend the following changes, which should not stop us deploying the german version. 
"Was repariert werden muss" -> "Was uns droht" 
"Verbreite die Kampagne!" -> "Spread the word" 
"Die Europäische Union hat 2015 einer Verordnung zur Netzneutralität zugestimmt …" -> "Die Europäische Union hat 2015 einer Verordnung zur Netzneutralität **beschlossen** …"

**Comment by musha68k** [comment]
Just FYI, the corresponding nginx rewrite rules have been changed on production and the translation [is live](https://savetheinternet.eu/de/) ([German](https://github.com/Netzfreiheit/STI-UI/blob/master/active_languages.conf#L2)).
