### ISSUE TITLE
change Facebook sharing image

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#123]
The Facebook sharing image shows the logo of Aykit instead of the logo of the campaign. 
(left hand side Facebook share button) 

https://www.facebook.com/sharer/sharer.php?s=100&p%5Burl%5D=http://www.savetheinternet.eu/&p%5Bimages%5D%5B0%5D=http://www.savetheinternet.eu/img/thumbnail.png&p%5Btitle%5D=Help%20Save%20the%20Internet&p%5Bsummary%5D=Your%20freedom%20online%20is%20threatened%20by%20EU%20proposals.%20The%20fight%20for%20an%20open%20Internet%20is%20happening%20right%20now%20in%20Brussels

This should show a version of the header share image or just the title of the website

**Comment by musha68k** [comment]
I don't know why this is happening, anyone with more Facebook experience please chime in..

The opengraph / twitter meta tags have been specified as such:

```
<meta property="og:image" content="https://savetheinternet.eu/images/save_the_internet_logo_headline@2x.png" />

<meta name="twitter:image" content="https://savetheinternet.eu/images/save_the_internet_logo_headline@2x.png">
```

See [here](https://github.com/Netzfreiheit/STI-UI/blob/master/themes/sti/layouts/partials/site-header.html#L14)

**Comment by burnoutberni** [comment]
I guess the wrong picture is still cached by Facebook. Try: http://stackoverflow.com/questions/1138460/how-does-facebook-sharer-select-images-and-other-metadata-when-sharing-my-url

**Comment by PublicScam** [comment]
https://developers.facebook.com/tools/debug/og/object/
og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. Image 'https://savetheinternet.eu/en/images/aykit.png' will be used instead.
There are a few other errors, too.

**Comment by PublicScam** [comment]
@socialhack 0127d5e067a26bc178a320c9fe3c7c20fc19be96 might fix this. We need to deploy and get facebook to catch the new image.

**Comment by musha68k** [comment]
@PublicScam I deployed the latest commits, please feel free to close this issue if FB is picking up the changes - thanks!

**Comment by PublicScam** [comment]
The image was fetched, although it doesn't seem right to me. Is it indended to show a small section only?

**Comment by musha68k** [comment]
I don't have a FB account, could you post a screenshot?

The FB docs seemed to imply it would be more "clever" than that:

https://developers.facebook.com/docs/sharing/best-practices#sharing-best-practices-for-websites

**Comment by PublicScam** [comment]
Here, you can even see it without an account:
https://developers.facebook.com/tools/debug/og/object/?q=savetheinternet.eu
Have a look at the bottom of the page.

**Comment by musha68k** [comment]
Thanks for that @PublicScam - I'm closing this for now as the new image has the exact recommended dimensions now.
