### ISSUE TITLE
Add akvorrat.at as STI Member

### ISSUE THREAD

**Issue by Sonstwer** [Netzfreiheit/STI-UI#127]
![akvorrat_logo_600x600](https://cloud.githubusercontent.com/assets/5865276/14606156/2b3ab10c-057c-11e6-937b-16bafdd52d11.png)

further questions -> office (a) akvorrat (.) at

**Comment by PublicScam** [comment]
Fixed in fd2f5038fbe432211c513d9c7b6fa3235bbc66df
