### ISSUE TITLE
Add Wikimedia Austria ( https://wikimedia.at ) as STI Member

### ISSUE THREAD

**Issue by Sonstwer** [Netzfreiheit/STI-UI#128]
Link:
https://www.wikimedia.at/
Link to Logo:
https://commons.wikimedia.org/wiki/File:Wikimedia_%C3%96sterreich_logo.svg

**Comment by PublicScam** [comment]
Fixed in fd2f5038fbe432211c513d9c7b6fa3235bbc66df
