### ISSUE TITLE
Facebook Circular Redirect Path

### ISSUE THREAD

**Issue by PublicScam** [Netzfreiheit/STI-UI#130]
Facebook complains about a Circular Redirect Path. This happens when the HTTP 302 points to some document that redirects back to the original document. 
In our case, the redirection of savetheinternet.eu/ will target a document based on the clients language, let's take savetheinternet.eu/en/ for example. Every document, however, contains a og:url with the value 'savetheinternet.eu/'. Facebook tries to follow it and instantly gets redirected again.
I don't know exactly why this problem is malicious, because at some point the crawler decides for a page, but Facebook complains about it and states that it should be fixed.

To fix this issue, we could either exclude Facebook from redirecting via 302 (I'm not sure if it could read the page then) or set all og:url values to 'savetheinternet.eu/en/'

**Comment by musha68k** [comment]
I hope [this commit](https://github.com/Netzfreiheit/STI-UI/commit/c503bbfe685f4d86d0e47274e27dacc1f851d242) has fixed this.

**Comment by PublicScam** [comment]
The '/' was missing in the url tags. Therefore, the 302 still lead to a loop.
