### ISSUE TITLE
Questionnaire iframe: Server Error in '/' Application

### ISSUE THREAD

**Issue by joelpurra** [Netzfreiheit/STI-UI#133]
While this belongs to the backend, it propagates to the frontend. Would it make sense to display an error message, or retry loading the iframe after a minute if it didn't succeed the first time?

Also, there should be a link from this repo to the backend repo. Couldn't see one in the readme, nor easily find one in the issues (searching for "backend"). Hope this is better than nothing.

https://consultation.savetheinternet.eu/en/

> Server Error in '/' Application.
> 
> Compilation Error
> 
> Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 
> 
> Compiler Error Message: CS0121: The call is ambiguous between the following methods or properties: 'STI.STIExtensions.GetTooltipValue(Umbraco.Core.Models.IPublishedContent, string)' and 'STI.STIExtensions.GetTooltipValue(Umbraco.Core.Models.IPublishedContent, string)'
> 
> Source Error:
> 
> 
> Line 37:                                 <div class="checkbox">
> Line 38:                                     <input id="@id" name="@id" type="checkbox" value="1" @checkedAttr />
> Line 39:                                     <label for="@id">@element.GetTooltipValue("title") <a href="#" class="expand-arrow"><i class="fa fa-caret-down"></i></a></label>
> Line 40:                                     <div class="predefined-message-preview">
> Line 41:                                         <p>@element.GetTooltipValue("response")</p>
> 
> Source File: D:\home\site\wwwroot\Views\Partials\_questions.cshtml    Line: 39 
> 
> 
> Show Detailed Compiler Output:
> 
> Show Complete Compilation Source:
> 
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by ondrejpialek** [comment]
This has been resolved on our side. Total downtime 13 hours :(

**Comment by joelpurra** [comment]
@ondrejpialek: so, where do I find the backend repo?

**Comment by ondrejpialek** [comment]
Oh sorry I thought you see the referenced issue here. Our repo is still private because it contains sensitive information such as connection strings. I was planning to make it public before I left for vacation but needed to purge the connection strings from Git history first. I got back a few days ago but still busy catching up. I will add you to the repo for the time-being as a temporary solution, before we make it public.

**Comment by ondrejpialek** [comment]
@joelpurra done, you should be able to access https://github.com/EndzoneSoftware/STI now

**Comment by joelpurra** [comment]
@ondrejpialek: oh, you're right -- the issue is (now?) linked above your comment. Thanks!
