### ISSUE TITLE
[SL] Missing translation: Button "Take Action"

### ISSUE THREAD

**Issue by PublicScam** [Netzfreiheit/STI-UI#154]
[The Slovenian site](https://savetheinternet.eu/sl/) is missing a translation. The big button "Take Action" was not translated appropriately. Does someone know a native speaker to fix that problem?

Google Translate is not an option! As this site gets more popular every day, we should not rely on a tool that's not reliable.

**Comment by socialhack** [comment]
You can find a translation here: https://twitter.com/socialhack/status/738118515501195265

**Comment by PublicScam** [comment]
I wasn't sure since he said he's not an expert.
