### ISSUE TITLE
[FR] Missing translation: Why should I care about traffic management?

### ISSUE THREAD

**Issue by PublicScam** [Netzfreiheit/STI-UI#155]
[A French paragraph](https://savetheinternet.eu/fr/faq/#why-should-i-care-about-traffic-management) of _Why should I care about traffic management?_ is missing translation. In [the English version](https://savetheinternet.eu/en/faq/#why-should-i-care-about-traffic-management), the part consists of three paragraphs, the French part has two only. I assume the first paragraph is missing.

For now, I placed the message _Something is missing here_ in there to let the readers know the following text might not read like it should.

It would be great if a native speaker could translate it for our french friends.

**Comment by piks3l** [comment]
I sent the French translation of this paragraph by email :) should be good and pushed intro prod by now :)

**Comment by PublicScam** [comment]
Hello, what address did you send the mail to? I didn't receive any, I checked twice. Could you send it to my git address please? publicscam /at/ gmx.at
Thanks a lot!

**Comment by socialhack** [comment]
copy-paste monkey delivers: 

EN: 
Traffic management affects your everyday Internet experience. When your
Netflix video is endlessly buffering, your Internet-Telephony call is
breaking off or an online game is unplayable, traffic management by your
Internet provider can be the cause.

FR: 
La gestion du trafic affecte tous les jours votre navigation Internet.
Lorsque votre vidéo Netflix ne charge pas, quand votre appel
téléphonique via Internet coupe tout le temps ou quand il est impossible
de jouer à un jeu en ligne, la gestion du trafic par votre fournisseur
d'accès Internet peut en être la cause.
