### ISSUE TITLE
add open-medias logo on the STI website

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#157]
link: https://openmedia.org
logo: ![openmedia-2015-logo_high-res 3](https://cloud.githubusercontent.com/assets/278564/15868549/9dbf37a0-2ce8-11e6-90e5-8eb62d801fc8.png)

**Comment by PublicScam** [comment]
Fixed by 5c396501ae601d92e9482595095dc4671ab9bddb
