### ISSUE TITLE
set og:image

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#163]
user comment: 

> it seems there is no og:image in the open graph defined -
> 
> no image is shown when sharing your site in Facebook
> 
> https://developers.facebook.com/tools/debug/og/object/
>

**Comment by PublicScam** [comment]
In commit 70e82ff6f706b806b294699385c0379c150f8873 Oskar removed `images/save_the_internet_logo_headline_sharing.png` accidentally I assume. I'll try to get it back up.
