### ISSUE TITLE
add yT video

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#164]
Please add this youtube video in the video section before john oliver of all language versions of STI, except the Romanian one. 
https://www.youtube.com/watch?v=nv3DeyqZzOg&feature=youtu.be

**Comment by PublicScam** [comment]
@socialhack Why is it important that this video is not shown on the Romanian page?

**Comment by socialhack** [comment]
Please fix this urgently!!! 

The video should have been on the site almost a week ago. Your question should not have blocked the rollout of this enhancement. You know how to reach me.

**Comment by PublicScam** [comment]
So what about the question? The video section is the same for **all** languages.
