### ISSUE TITLE
pt version not deployed?

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#166]
the Portuguese version of the website seems not to work, it points to the english
pt -> en

**Comment by PublicScam** [comment]
Can you specifiy any further?
https://savetheinternet.eu/pt/
PT version seems to work for me.

**Comment by sqrt2** [comment]
Apparently whoever deployed it forgot to add the pt language version to the webserver configuration. I fixed that a minute ago, which is why it's working now.
