### ISSUE TITLE
Missing: BEREC stakeholder questions

### ISSUE THREAD

**Issue by PublicScam** [Netzfreiheit/STI-UI#190]
On the index page, the following paragraph is missing in a few translations,

> Recently, BEREC organised face-to-face meetings with stakeholder groups. We have translated the questions that BEREC asked stakeholders (see here and here) in those meetings into plain English and added few others when we felt this was necessary.

Affected languages are
- FI
- LV
- DE

**Comment by socialhack** [comment]
This sentence is out of date and was therefore deleted in the german translation and the subsequent translations built upon it.

**Comment by PublicScam** [comment]
@socialhack Well then, why wasn't it deleted in other languages? You could have notified me.
