### ISSUE TITLE
Tell me clearly; what's the true point of your website?

### ISSUE THREAD

**Issue by fastcopy** [Netzfreiheit/STI-UI#198]
I've already signed many websites, for example EFF's Rule41(IIRC).
There's TOO MANY websites for gathering, I wonder why do you create your own for this.

You could use EFF.org's platform, or change.org.

There's too many for this, and people are tend to miss important things easily.
Why would I want to imput personal information to such a YOUNG domain?

Your IP:
Hide by Cloudflare. Maybe you are working with NSA to collect people's email. Care-about-privacy is being flagged as potential suspect in the USA.

Your SSL:
Using Cloudflare's free SSL. Again, nobody can't verify your identity. Your original server maybe using HTTP, allowing anyone to collect your information posted(that's how Universal FREE SSL works).

Your Domain:
Hidden Whois. DUH!
"For privacy reasons, the registration data of private persons is not fully disclosed."

**Comment by fastcopy** [comment]
> 168,940 	PEOPLE HAVE SENT MESSAGES 	

I must say, these people SHOULD verify the website BEFORE POSTING ANY PERSONAL INFORMATION.
Check Server's IP address. Connection type. Domain Whois. Reputation.

**Comment by sqrt2** [comment]
We use Cloudflare for stability purposes. The connection between Cloudflare caches and our webserver is SSL-secured, we know what we're doing. EURid (the .eu domain registry) hides whois information as a matter of EU law, we have no influence over this.

Feel free to contact info@savenetneutrality.eu if you think the information we have on our website about who we are and what our privacy policy is is insufficient. Please do not abuse a bug tracker for this purpose.

**Comment by PublicScam** [comment]
> Your IP:
> Hide by Cloudflare. Maybe you are working with NSA to collect people's email. Care-about-privacy is being flagged as potential suspect in the USA.

Our IP is hidden by the way Cloudflare's reverse proxies work, it's not the reason we use it, though. @sqrt2 pointed out correctly that we use Cloudflare for stability purposes. If you look closely, there are ways to indeed find out the real IP in our case.
And just to point this out: NSA collecting email addresses over such campaign would be inefficient. I guess there are better ways to do this.

> Your SSL:
> Using Cloudflare's free SSL. Again, nobody can't verify your identity. Your original server maybe using HTTP, allowing anyone to collect your information posted(that's how Universal FREE SSL works).

We are pretty concerned about information security and privacy. There's a reason why we store data in Austria but not in US. Using change.org, you would not even know where your data is stored after all, they're allowed to store them in any of their establishments.
