### ISSUE TITLE
Typos Questionnaire

### ISSUE THREAD

**Issue by yaoyuanpa** [Netzfreiheit/STI-UI#22]
Multiple Choice part:

All the questions should start with a capital letter at the beginning, this also helps with readability
Question 5: prioritise

Open Questions page 1:

Question 1: that can be GIVEN (N); RELIABILITY (L)
Question 2 in the dropdown: the three hyphens should be – (Alt) not -
Question 3 in the dropdown: after specialised services there’s a lost quotation mark :simple_smile:
also, it says “user’s rights", while in the dropdown of Question 4 it says “users’ rights"

Open Questions page 2:

Question 2: the hyphen should be – (Alt) not - 
Question 3 in the dropdown: regardless of the type of content being accessed (PERIOD) ISPs
Question 4: … as a user? (SPACE) Please (NO COMMA) provide examples.
Question 5: For example: Traffic (CAPITAL T) management, (COMMA, NO SEMICOLON)
Question 5 in the dropdown: “transparent” not ‘transparent – wrong quotation mark; transparency is one of(SPACE) the criteria
Question 6 in the dropdown: would be(SPACE)misleading

**Comment by yaoyuanpa** [comment]
If you guys could take care of this while working on the other questionnaire issues, that would be great! @ondrejpialek @filipesousa20

**Comment by filipesousa20** [comment]
Hi @yaoyuanpa this seems to be a content issue. Who is tasked with managing content?

**Comment by filipesousa20** [comment]
These have been fixed:


Multiple Choice part:

~~All the questions should start with a capital letter at the beginning, this also helps with readability
Question 5: prioritise~~

Open Questions page 1:

~~Question 1: that can be GIVEN (N);~~ RELIABILITY (L)
~~Question 2 in the dropdown: the three hyphens should be – (Alt) not - ~~
~~Question 3 in the dropdown: after specialised services there’s a lost quotation mark :simple_smile:
also, it says “user’s rights", while in the dropdown of Question 4 it says “users’ rights"~~

Open Questions page 2:

~~Question 2: the hyphen should be – (Alt) not - ~~
~~Question 3 in the dropdown: regardless of the type of content being accessed (PERIOD) ISPs~~
~~Question 4: … as a user? (SPACE) Please (NO COMMA) provide examples.~~
~~Question 5: For example: Traffic (CAPITAL T) management, (COMMA, NO SEMICOLON)~~
~~Question 5 in the dropdown: “transparent” not ‘transparent – wrong quotation mark; transparency is one of(SPACE) the criteria~~
~~Question 6 in the dropdown: would be(SPACE)misleading~~

**Comment by yaoyuanpa** [comment]
There are still typos in the questionnaire:

Typos 

Multiple Choice: 
Qu1, Explanatory text: Wrong hyphen; not - - but – (Alt+hyphen) should be used
startup or non-commercial service -- no matter how small or well funded -- has the potential 
Qu 5: throttle or prioritize (PRIORITISE)


Open Questions 1
Qu 3: Any commercial practices which limit user’s rights (USERS’ RIGHTS)

Open Questions 2
Qu 3: maximum and minimum speed in a user-friend way (USER-FRIENDLY)

**Comment by socialhack** [comment]
Thanks a lot for showing a grammar blind person like me those mistakes. I fixed them all! :+1:
