### ISSUE TITLE
Position of Timeline graphic

### ISSUE THREAD

**Issue by maltefiala** [Netzfreiheit/STI-UI#39]
Merging into blue is nice but leaves a lot of space to the left. We need to weigh what option to use.

IE11 does not merge, see screenshot attached
![timeline](https://cloud.githubusercontent.com/assets/526184/13897655/9d99fef0-edb8-11e5-9e1f-31a50ab45507.png)

**Comment by yaoyuanpa** [comment]
Updated map and changed positioning on image, @musha68k pls check colours and align center

**Comment by maltefiala** [comment]
Fixed: https://github.com/Netzfreiheit/STI-UI/commit/2c71611996f8964cd9a4906526ad0ff7abc6189b
