### ISSUE TITLE
highlight current step in questionnaire

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#45]
the navigation bar for the four chapters should highlight the current chapter

**Comment by yaoyuanpa** [comment]
The current step is highlighted with a triangle as shown in the mockup. As far as I know, @musha68k already implemented it (https://beta.savetheinternet.eu/en/step-1/) – I'm not sure what's not working here.
![screen shot 2016-03-22 at 10 41 50](https://cloud.githubusercontent.com/assets/17917499/13947482/20f31962-f01b-11e5-9952-aa7ae2e458f5.png)

**Comment by yaoyuanpa** [comment]
Compared to the mockup it's a little small now... would it be easy to make a little bigger as shown above?
@musha68k
