### ISSUE TITLE
Make "Act Now" on top of front page more prominent

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#47]
users didn't realise that they could click the take action. make it more prominent and inviting.

**Comment by yaoyuanpa** [comment]
I think we need to make it more button-like. Currently, the dropshadow is missing and the placement suggests that it is just a style element. Adding more shadow and making the overlap more clear should help – see attachments for comparison 
![screen shot 2016-03-22 at 10 48 30](https://cloud.githubusercontent.com/assets/17917499/13947711/50fc556e-f01c-11e5-8544-38a39aea6598.png)
![screen shot 2016-03-22 at 10 49 53](https://cloud.githubusercontent.com/assets/17917499/13947712/50fd4a32-f01c-11e5-8116-647b48bf7a57.png)

**Comment by Maryantfp** [comment]
The new Act-now is much better, but it should be detached the number of respondents and the count-down.
A flashy, attractive ACT-Now bottom should be added in the middle
