### ISSUE TITLE
Can we add endzone.io logo to the site footer (With friendly support from)?

### ISSUE THREAD

**Issue by ondrejpialek** [Netzfreiheit/STI-UI#56]
Hi @socialhack, would it be possible to include our logo among the organizations that helped with the website (With friendly support from)? 

![logos](https://cloud.githubusercontent.com/assets/580850/13906708/bfda7d7a-eedd-11e5-836e-fdb1c5d95263.png)

**Comment by yaoyuanpa** [comment]
![screen shot 2016-03-22 at 13 11 45](https://cloud.githubusercontent.com/assets/17917499/13951279/1bd95b48-f030-11e5-8368-e27ff7763236.png)

**Comment by ondrejpialek** [comment]
Looks great @yaoyuanpa , thanks a lot! BTW, would you mind sharing the source (or just the png file) for the BW logo with us, in case we needed this in the future? I will buy you a beer once we see each other ;)
