### ISSUE TITLE
reorder the parts of the website 

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#59]
move the < long text at the header > ("In 2015, the European […] future of net neutrality in Europe.") to the bottom after < spread the word > and the < logos of NGOs > 
move the video section between the < questionnaire > and the < spread the word > section

**Comment by maltefiala** [comment]
@socialhack , This changes a lot regarding visual flow and appearance. We would need to adapt the whole visual flow if we want to do these changes right. Without any further adaption, it would look like following screenshot (which of course is not good): 
![save_the_internet_ _save_the_internet_-_2016-03-22_14 36 54](https://cloud.githubusercontent.com/assets/526184/13953990/150079d2-f03f-11e5-9900-8f3a4f7f06f1.png)


A less radical move would be to only change the position of the long information text, see following screenshot:
![save_the_internet_ _save_the_internet_-_2016-03-22_15 04 27](https://cloud.githubusercontent.com/assets/526184/13954062/71b2cf86-f03f-11e5-914a-4f3adcf0312e.png)


All in all it's a huge change that is easily done code wise but needs a lot of work (especially in the details) in terms of visual flow.

**Comment by yaoyuanpa** [comment]
Are you sure you want to do this? @socialhack This would mean there's no narrative flow – no introduction, no main part, no finish. Putting a lot of information and useful material AFTER the action part would make the user feel that they weren't fully introduced to all parts of the issue. 

It might be that you're worried that it takes too long to reach the questionnaire, but we have 3 opportunities that can take you there right away: Send a message in the navigation bar, the Act Now button and the Your Input link before further information. If that is still not enough we could make the Act Now button follow you down when scrolling (although in my opinion it's a little pushy) 

I think it would make sense to replace the "In 2015.... " headline for something more clear and catchy, like  "What's going on" (would fit with the second "What needs to be fixed" language-wise as well)...

I like @maltefiala idea of putting the video section further up though, moving pictures are always good :)

Sorry for the wall of text, but this is a big thing! Please let us know!

**Comment by socialhack** [comment]
Your alternative proposal is actually the way we imagined it. Please go ahead with the implementation. Regarding implementation, shouldn't it be just a simple copy&paste of the html code or do you cascade div's? 

@yaoyuanpa: The subtitle "What is going on" is fine. We can use that.

**Comment by maltefiala** [comment]
Dear Thomas, do you mean the:

"A less radical move": Second screenshot of my last post

or

"alternative proposal" mentioned via e-mail:
Collapse everything between "The legislators decided to leave the responsibility for claryifing the uncertainties of the text to the telecoms regulators." and "BEREC needs your input before they decide on the future of net neutrality in Europe."


The "less radical move" is
- easily done code wise but needs 
- a lot of work in terms of visual design (especially in the details)

The "alternative proposal" is:
- easily done at code level
- easily done at visual design level


Depending on your decision, we will post all follow up questions regarding details here afterwards.
