### ISSUE TITLE
Polling endpoints for counter

### ISSUE THREAD

**Issue by musha68k** [Netzfreiheit/STI-UI#6]
@ondrejpialek could you let me know about the specific endpoints I'd need to poll from here?

<img width="235" alt="screen shot 2016-03-17 at 14 36 52" src="https://cloud.githubusercontent.com/assets/95477/13847479/b69bbb58-ec4d-11e5-9226-a25a3dc8dcbb.png">

**Comment by maltefiala** [comment]
Done: https://github.com/Enproduktion/STI-mailcounter
