### ISSUE TITLE
stop video playback on video switch

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#61]
If possible, stop video playback if user navigates to another video. Otherwise the audio continues to playback in the background.

**Comment by maltefiala** [comment]
I suggest switching to images, see #30 , what do you think?

**Comment by socialhack** [comment]
No, if you playback a video and and navigate to a new video the currently playing video should stop. 

Javascript should do the trick, just have a listener on the navigation: 
`$('.carousel-control').click(function () { alert(1); });`
and stop the video inside the closure function 
`https://developers.google.com/youtube/js_api_reference?hl=de#GettingStarted`
