### ISSUE TITLE
Add DFRI as a supporter

### ISSUE THREAD

**Issue by joelpurra** [Netzfreiheit/STI-UI#72]
Föreningen för Digitala Fri- och Rättigheter (DFRI) (@DFRI) from of Sweden would like to support savetheinternet, and add our logotype to the supporter list at the bottom of the page.

> [![Föreningen för Digitala Fri- och Rättigheter (DFRI)](https://www.dfri.se/wp-content/uploads/2015/01/dfri_logotype_https_orange_1024.png)](https://www.dfri.se/)
> Föreningen för Digitala Fri- och Rättigheter (SE)
> https://www.dfri.se/

Obviously the orange logotype isn't suitable for this campaign. We have our logotype on a couple of formats -- would any of these do?
https://www.dfri.se/dfri/media-och-press/

**Comment by socialhack** [comment]
This has been approved by the STI coalition. Please add DFRI.
