### ISSUE TITLE
infinite "loading questionnaire" 

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#83]
The "loading questionnaire" text does not disappear after the questionnaire has loaded. 
<img width="1053" alt="screen shot 2016-03-28 at 16 02 36" src="https://cloud.githubusercontent.com/assets/278564/14093089/3941a436-f500-11e5-913f-68711cf4b490.png">

**Comment by musha68k** [comment]
@socialhack just a quick update on this issue - I'm in contact with the backend team and @filipesousa20 is currently adapting the last changes which should resolve this issue (it's some changes to the the iframe javascript; communicating with the parent context so it "knows" when the page has been loaded successfully).
