### ISSUE TITLE
Ready for translations?

### ISSUE THREAD

**Issue by joelpurra** [Netzfreiheit/STI-UI#87]
A [script to get started with translation](https://github.com/Netzfreiheit/STI-UI/blob/master/translate.sh) of the site to a different language has been added, and translation instructions updated (842d7e93e7b0046f52e998158896e9d6a96abc16).

- Does this mean that everything is ready for translation, or should translators hold?
- Is there a mechanism to know:
  - when to start?
  - which strings/parts to update so a translation doesn't get outdated?

**Comment by musha68k** [comment]
Hi @joelpurra we are pretty much ready for translations yes but there is no specific mechanism for tracking changes.

Maybe we should work through pull requests on a feature/translation-[TWO_LETTER_CODE] branch basis? Does that sound reasonable?

**Comment by joelpurra** [comment]
> Hi @joelpurra we are pretty much ready for translations yes

Good! Do ping when ready. ("Ready" is of course relative ;)

> but there is no specific mechanism for tracking changes.
> 
> Maybe we should work through pull requests on a feature/translation-[TWO_LETTER_CODE] branch basis? Does that sound reasonable?

I don't think it's possible to use "real" branches for the translations -- but perhaps _marker branches_ (or tags) `translation-XX`, pointing to the most recent commit on `master` which has been translated to the language. The marker branches would have to be updated by repo admins once a translation pull request has been merged. Was that what you meant?

**Comment by socialhack** [comment]
Re When: 
We will launch this week and then I'll give the go for translations. 
Re tags: 
A translations is always a fork of the main version (english) at the time of a stable release. Later changes made in this english version are often not taken over in other languages, they divert. 
Could we somehow mark the base english version from which a translation forks so that we can see a diff of all changes in the english version which a translator has to adopt in its language version?

**Comment by joelpurra** [comment]
@socialhack: Here's a brain dump on a possible approach, using Swedish/`sv` as an example:

It would be nice to have some kind of _marker branches_ though, pointing to the most recent commit (on `master`) which has been translated. Then a diff between `translation-sv` and `master` for the base language (English) could be done to reveal changes which might need attention. Here assuming only `themes/sti/layouts/` and `content/en/` would need to be "monitored".

```bash
git diff master translation-sv "themes/sti/layouts/" "content/en/"
```

When a translation needs to be updated, look at the diff and then mirror the changes in the translated documents. Get the latest code in your own repository fork, commit to the fork, then issue a pull request against [Netzfreiheit/STI-UI/blob/master](https://github.com/Netzfreiheit/STI-UI/blob/master/). Assuming the pull request gets accepted, the marker branch `translations-sv` should be updated (by repo admins) to point to the commit on master which the pull request was made to (which might not be the most recent commit if it took time).

A problem might of course be that changes are too large (but presumably spread across commits) to be easily handled using a simple diff against `master`. A "stepwise" per-commit diff could be performed against `master~10`, `master~9`, ... -- but it would require more work, and quite possibly several commits to make sense in the translated files' diffs. (This is similar to having merge issues, except with manually copied code.)

**Comment by socialhack** [comment]
Hi @joelpurra this sounds like a feasible solution to me, but I am not a git expert. 

Could you add this description to the HowTo in the README.md in user-friendly, understandable terms (at best without command line)?

**Comment by joelpurra** [comment]
@socialhack: if others also agree that this is a good enough approach, then I'd be happy to adapt and add them to the README. I don't use non-command line tools for git, so am unsure how to use those terms, but I'll try.

Should note that prior engagements might prevent me from working on this until Monday. Hope it's not too late for translators; at least the steps are already outlined above. Also feel free to adapt them without me.

**Comment by socialhack** [comment]
@joelpurra I'm not even sure if it is possible to at least mark the baseline version of the translation with the web interface. If it is not possible in the browser the command line will suffice. A third option would be that the person that merges the pull request with the translation sets the label at the right comment. 

I don't know when people start translating. I'd like to send an email out this week to let people know this task is now possible.

**Comment by katrinleinweber** [comment]
I tried just now and got "mkdir: layouts: No such file or directory" when running [translate.sh](https://github.com/Netzfreiheit/STI-UI/blob/master/translate.sh). Did that manually & started the German translation.

**Comment by musha68k** [comment]
@katrinleinweber Hi Katrin, sorry could you pull again - I hope the last commit fixes this issue.

**Comment by musha68k** [comment]
@joelpurra your workflow seems reasonable but when you say "marker branches" are we actually talking about git tags?

**Comment by joelpurra** [comment]
@musha68k: in this case either can be used. As the "marker"/"commit pointer" should be updated when new material has been translated, I would use a branch for the marker. Tags are usually static once created.

**Comment by musha68k** [comment]
🇪🇺 thanks @joelpurra and just FYI @katrinleinweber and I are currently testing this approach by working through the German translation - see here:

https://github.com/Netzfreiheit/STI-UI/tree/translation-de

**Comment by musha68k** [comment]
Does anyone have experience or *know someone* who might have with https://www.transifex.com or similar services? I'm pretty occupied at the moment but will evaluate them later in the evening myself to check for feasability. Just puttng this out here real quick because @AlfaSchz (🎩👌) has rightfully highlighted that our approach to translations might not be the most inclusive ... well IMHO he is right, *translating text into other languages should become much more user-friendly/inclusive*.

So again (technical) 2c very much welcome from my side here - por favor und merci!

**Comment by katrinleinweber** [comment]
I know that, [Crowdin](https://crowdin.com/) and [OneSky](https://www.oneskyapp.com/how-it-works/translation-management-system/) from the translator/user perspective.They are all fine IMHO. @timpritlove or @eteubert probably know more about OneSkye from the admin perspective ;-)

**Comment by joelpurra** [comment]
@musha68k, @katrinleinweber: great! It's quite interesting to see how "far" individual translations have gotten, using the ["network" github ui feature](https://github.com/Netzfreiheit/STI-UI/network).

## General command-line `git`/`hub` helpers:

Thought I'd put these tips here, since we're playing with branches and forks. It's clear that a proper translation service/tool should be used to make this translations user-friendly ;)

For local development/command-line, `git log` can be used to view the locally-known branch/fork "network."

```bash
git log --oneline --graph --decorate --abbrev-commit --all
```

I use the alias `gl`, among others.

```bash
alias gl='git log --oneline --graph --decorate --abbrev-commit --all'
```

Using [`hub`](https://hub.github.com/) it's also easy to pull in other's forks, check out pull requests for reviews among other things.

```bash
hub fetch katrinleinweber
```

```bash
hub checkout https://github.com/Netzfreiheit/STI-UI/pull/102
```

**Comment by musha68k** [comment]
FYI regarding the new boilerplate workflow - 've updated the corresponding section in the README and deleted the translate.sh as we don't need it anymore.

See [commit](https://github.com/Netzfreiheit/STI-UI/commit/846bcee21cd4bea4084e58d611fdbd7c0f45328b)

**Comment by musha68k** [comment]
See [README](https://github.com/Netzfreiheit/STI-UI/blob/master/README.md)
