### ISSUE TITLE
Timeline's text

### ISSUE THREAD

**Issue by Maryantfp** [Netzfreiheit/STI-UI#89]
"(tbc)" after RespectMyNet and after "STI relaunch" should be deleted. Respectmynet.eu was relaunched on 3 March (not on 2 March).
Theresia (EDRi) is changing that and the new sharepic will appear under this link: https://edri.org/files/netneutrality/NN_infographics_berec_timeline.png

**Comment by socialhack** [comment]
Please let us know here in this thread once Theresia uploads the new graphic.

**Comment by Maryantfp** [comment]
It's done. The new graphic now appears under the link indicated
