### ISSUE TITLE
Country selector for newsletter sign-up?

### ISSUE THREAD

**Issue by musha68k** [Netzfreiheit/STI-UI#91]
@socialhack I believe there might have been some country specific mailing lists before, is this something we need to take care of?

Referencing the snippet you sent on the corresponding issue: https://github.com/Netzfreiheit/STI-UI/issues/48

**Comment by socialhack** [comment]
You are right, we used to have something like this. I am still in discussion with Access here at RightsCon how we can get such a functionality back. So far the simple mailman newsletter is all we have. I come back to this once we are clear what solution we want.
