### ISSUE TITLE
autoplay youtube videos when iframe is inserted 

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#92]
see http://stackoverflow.com/questions/7281765/youtube-iframe-embed-auto-play

**Comment by PeterTheOne** [comment]
Adding `?autoplay=1` to the videourl attribute should do the job.

**Comment by musha68k** [comment]
Just FYI, autoplay only works on Desktop and certain mobile browsers only because of a hard constraint (cellular downloads etc.) see here:

https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations
