### ISSUE TITLE
distinguis links from glossary terms in questionnaire

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#93]
currently links and glossary terms with tooltips are both displayed as links. A visual distinction (underline or yellow background color) for glossary terms would be good.

**Comment by yaoyuanpa** [comment]
It should be clear, but not too distracting. Text turns white on hover.

![screen shot 2016-03-31 at 21 03 07](https://cloud.githubusercontent.com/assets/17917499/14187583/13a2ddfe-f784-11e5-8221-489360ed42a4.png)

**Comment by yaoyuanpa** [comment]
Also, the font-size of the glossary terms should be the same as the questionnaire body text @musha68k @filipesousa20
