### ISSUE TITLE
[urgent] Remove the markup language in Questions from the final e-mail text

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#94]
If there are Glossary words in the title of an open question (which we would really like to use) the whole markup is then in the final e-mail. Please remove the markup language and leave the explained term itself in the composed e-mail body in the 4th step.

/// Intended Output:

Dear Sir or Madam,

Please take this Stakeholder comment regarding the BEREC net neutrality guidelines creation into consideration.

Is there a demand for specialised service? Which services should be allowed this special treatment?
No there is no Demand

What could be the positive and negative impacts of specialised services on future innovation and openness of the Internet?
Yes there are impacts

Is there a demand for “commercial practices” such as zero-rating? Could these limit your rights as an end-user? Please provide examples.
Zero Cool

Kind regards,
A concerned citizen

/// Current Output:

Dear Sir or Madam,

Please take this Stakeholder comment regarding the BEREC net neutrality guidelines creation into consideration.

Is there a demand for [specialised services](Specialised service is any service provided over the Internet access connection that is given additional quality by the Internet access company. Under the Regulation, this optimisation must be objectively necessary for the electronic service being accessed and not simply granting priority to the service. The access provider must also ensure that there is enough capacity so that the quality Internet access is not undermined. The necessity should be verified by the national telecommunications regulatory authority. In short, a "specialised service" cannot be a discriminatory "fast lane".)? Which services should be allowed this special treatment?
No there is no Demand

What could be the positive and negative impacts of [specialised services](Specialised service is any service provided over the Internet access connection that is given additional quality by the Internet access company. Under the Regulation, this optimisation must be objectively necessary for the electronic service being accessed and not simply granting priority to the service. The access provider must also ensure that there is enough capacity so that the quality Internet access is not undermined. The necessity should be verified by the national telecommunications regulatory authority. In short, a "specialised service" cannot be a discriminatory "fast lane".) on future innovation and openness of the Internet?
Yes there are impacts

Is there a demand for “commercial practices” such as [zero-rating](Zero rating is a commercial practice, for which data downloaded from certain applications or services is not counted towards a subscriber's monthly download limit. Zero rating treats different traffic in different ways, in order for some to be offered at one price and some to be offered at a different price. Although technically different from classic net neutrality violations, it is identical from practical purposes, as it allows the internet access provider to influence what applications and services are used and which are not.)? Could these limit your rights as an end-user? Please provide examples.
Zero Cool

Kind regards,
A concerned citizen

**Comment by musha68k** [comment]
@filipesousa20 could please update the corresponding content on the backend side? Thank you.

The site is now live btw :) https://savetheinternet.eu

**Comment by maltefiala** [comment]
Not frontend related, see https://github.com/EndzoneSoftware/STI/issues/14
